### ISSUE TITLE
Extension doesn't work.

### ISSUE THREAD

**Issue by sargon2** [tostc/CPP-include-refactor#8]
I have a C++ project that uses CMake with Ninja on Windows.  After enabling the extension, when I rename a file:

1. Nothing related to refactoring or changing any code happens.
2. "Parsing Opened Files" hangs and spins forever.

Uninstalling and restarting the extensions causes parsing to work again.

**Comment by tostc** [comment]
How large is your project? Since this extension didn't use any kind of cache or index and operates directly on every `hpp, h, hxx, c, cpp, cxx` file. This could be take a very long time on slow drives or systems to refactor all files. The "Parsing Opened Files" message comes from the default C++ Extension from Microsoft. Since I only show a message on error or if all files are refactored successfully.
I use a simple regex to find every include occurence, without any parsing library like clang.

**Comment by sargon2** [comment]
> How large is your project?

Just my source code:

```
proj/source> wc **/*.(hpp|h|hxx|c|cpp|cxx) | grep total
7781  23285 275986 total
```

Including all `vcpkg` dependencies (they're in the project folder, but not in the source folder):

```
proj> wc **/*.(hpp|h|hxx|c|cpp|cxx) | grep total
5604778  20512090 238789761 total
```

I added my `vcpkg` folder to `cppIncludeRefactor.excludeDirs` and that fixed the issue.  Sorry about that, I should have realized!

Before excluding vcpkg, I waited a long time for it to complete and it never did.  After excluding it, it completed in about 20 seconds.
